### ISSUE TITLE
Documentation Site

### ISSUE THREAD

**Issue by ghost** [brian978/Acamar-Framework#20]
Hello, i have tested this framework with example application and it seems to me good as a framework. Unfortunately, the documentation site does not work.

Could you put it back online please?

**Comment by brian978** [comment]
Hello,

Unfortunately, I don't have access to the documentation anymore, but you can use the tests to see how to use the components. Be sure to check the skeleton application, for examples, as well: https://github.com/brian978/Acamar-SkeletonApplication

**Comment by ghost** [comment]
It does not matter anymore. During these days of vacation I have decided to go permanently to ASP, because of all the developers who abuse that damn cancer composer.
